language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libpcre3-dev zlib1g-dev libcurl4-openssl-dev
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh

script:
  - CI=1 make
  - make tests
